### ISSUE TITLE
Can not build project.

### ISSUE THREAD

**Issue by ducpt2** [7kfpun/BitcoinReactNative#1]
I try to build your project and i have a issue:
Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/Bitcoin.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist.

Any helps? Thank you.

**Comment by 7kfpun** [comment]
I have checked it. Seems need to run `react-native link` to ensure all packages linked. Please try again.

**Comment by ducpt2** [comment]
Hi,
Thanks for your response, but it has same problem above. Any suggest?

**Comment by 7kfpun** [comment]
Could you clone again or pull the latest code?

**Comment by ducpt2** [comment]
I follow your setup:
Clone this repo $ git clone git@github.com:7kfpun/BitcoinReactNative.git
$ cd BitcoinReactNative
Copy and config the value $ cp app/config.example.js app/config.js
Install packages npm install
Run react-native link to make sure all packages linked

But no luck. Can you take a look? Still has same issue above.

**Comment by 7kfpun** [comment]
I have tried it. It works properly.
